---
spring:
  profiles: htwo
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1

---
spring:
  profiles: default
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: org.h2.Driver
