---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
    hikari:
      maximum-pool-size: 1

---
spring:
  profiles: htwo
  datasource:
    url: "jdbc:h2:mem:test;MODE=DB2;DB_CLOSE_ON_EXIT=FALSE;INIT=runscript from 'C:/Users/loren/Git/public/blog/cds-series/jdbctests/springjdbctests/srv/src/main/resources/schema.sql'\\;runscript from 'C:/Users/loren/Git/public/blog/cds-series/jdbctests/springjdbctests/srv/src/main/resources/init.sql'"
    driver-class-name: org.h2.Driver
